### ISSUE TITLE
It is not clear what this plugin actually does

### ISSUE THREAD

**Issue by dunyakirkali** [RishabhTayal/fastlane-plugin-hours#2]
Hi,

I'm curious to know, is this plugin actually recording time on the [hours for teams](https://www.hoursforteams.com/#/login) project?

**Comment by RishabhTayal** [comment]
It's not recording time on hours project. Its a simple plugin which creates a text file in your repo and writes time saved by `fastlane` to it. Every time you run a lane it will accumulate the time saved. 

Is that clear? I will update the readme.md.

**Comment by RishabhTayal** [comment]
I have updated [README.md](https://github.com/RishabhTayal/fastlane-plugin-hours#about-hours) to be more clear.

**Comment by dunyakirkali** [comment]
Thanks for the explanation
